language: generic

services:
  - docker

env: 
  - IMAGE_NAME="app"

script:
  - docker build .
  # - docker images | grep app
  # - docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
  # - docker build -t quay.io/[yourusername]/travis-quay-tutorial:$TRAVIS_BRANCH -t quay.io/[yourusername]/travis-quay-tutorial:latest .
  - docker images --format "{{.ID := index .0}}"
  - curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -i f2a855684cc3 .

# deploy:
#   provider: qu

after_success:
 - echo "Build successful.

after_failure:
 - echo "Build unsuccessful"