# specifying the runtime language and version
language: generic
# python:
#   - "3.8.2"

services:
  - docker

env: 

script:
  - docker build -t app .
  - docker images | grep app
  # - docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
  # - docker build -t quay.io/[yourusername]/travis-quay-tutorial:$TRAVIS_BRANCH -t quay.io/[yourusername]/travis-quay-tutorial:latest .
  - curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- app

deploy:
  provider: qu

after_success:
 - echo "Build successful.

after_failure:
 - echo "Build unsuccesful"